from odoo import api, fields, models, _



class PlcUpload(models.Model):
    _name = 'plc.upload'

    swdid_no = fields.Char('SWDID No')
    name = fields.Char('Customer Name')
    city = fields.Char('City')
    zipcode = fields.Char('Zipcode')
    state = fields.Char('State')
    phone_number = fields.Char('Phone Number')
    mobile_number = fields.Char('Mobile Number')
    contact_name = fields.Char('Contact Name')
    street_address = fields.Char('Street Address')
    test = fields.Char('test')
    installation_date = fields.Char('Installation Date')
    dep_region = fields.Char('DEP Region')
    ew_id = fields.Char('EW ID')
    time_zone = fields.Char('Time Zone')
    total_operating_hours = fields.Char('Total Operating Hours')
    total_gallons_used = fields.Char('Total Gallons Used')
    status = fields.Char('Status')
    bacteria = fields.Char('Bacteria')
    hardness = fields.Char('Hardness')
    ph = fields.Char('pH')
    iron = fields.Char('Iron')
    manganese = fields.Char('Manganese')
    tds = fields.Char('TDS')
    turbidity = fields.Char('Turbidity')
    uv_t = fields.Char('UV/T')
    epa1 = fields.Char('')
    epa2 = fields.Char('')
    epa3 = fields.Char('')
    epa4 = fields.Char('')
    epa5 = fields.Char('')
    epa6 = fields.Char('')
    epa7 = fields.Char('')
    epa8 = fields.Char('')
    item_model_1 = fields.Char('Item 1')
    item_model_2 = fields.Char('Item 2')
    model_sl_no = fields.Char('Serial Number')
    rp_item_1 = fields.Char('')
    rp_item_2 = fields.Char('')
    rp_item_3 = fields.Char('')
    rp_item_4 = fields.Char('')
    rp_item_5 = fields.Char('')
    user_1 = fields.Char('')
    user_2 = fields.Char('')
    user_3 = fields.Char('')
    pwd_1 = fields.Char('')
    pwd_2 = fields.Char('')
    pwd_3 = fields.Char('')
    operator_name = fields.Char('')
    op_street = fields.Char('')
    op_city = fields.Char('')
    op_state = fields.Char('')
    op_zip = fields.Char('')
    op_phn = fields.Char('')
    op_email = fields.Char('')
    op_lc_no = fields.Char('')
    op_notes = fields.Text('')
    dep_notes = fields.Text('')
    manufacturer_notes = fields.Text('')
    new_page = fields.Char('')
    daily_data = fields.Binary('')
    file_name = fields.Char("Filename")
    uv_line_ids = fields.One2many('plc.lines', 'plc_upload', string='UV Lines',)
    filter_line_ids = fields.One2many('plc.lines', 'filter_data_plc', string='Filter Data',)
    ccp_line_ids = fields.One2many('plc.lines', 'plc_upload_ccp', string='CCP',)
    alarm_line_ids = fields.One2many('plc.lines', 'plc_upload_alarm', string='Alarms',)
    service_line_ids = fields.One2many('plc.lines', 'service', string='Alarms',)

PlcUpload()

class PlcLines(models.Model):
    _name = 'plc.lines'

    ew_id = fields.Integer('')
    service = fields.Many2one('plc.upload','')
    plc_upload = fields.Many2one('plc.upload','')
    high_dp_filter1 = fields.Char('')
    fdpa = fields.Float('')
    lhr = fields.Float('')
    temp = fields.Float('')
    lamp_eol = fields.Char('')
    gpm = fields.Float('')
    max_gpm_exceeded = fields.Char('')
    high_dp_screen_filter = fields.Char('')
    uv_probe_2_failure = fields.Char('')
    lfa = fields.Float('')
    max_flush_cycle = fields.Char('')
    gmt = fields.Datetime('')
    toh = fields.Float('')
    startup_mode_timeout = fields.Char('')
    new_text1 = fields.Char('')
    status = fields.Char('')
    gpd = fields.Float('')
    date_utc = fields.Datetime('')
    dose = fields.Float('')
    dp1 = fields.Float('')
    ntu = fields.Float('')
    filter_2_expired = fields.Char('')
    new_text2 = fields.Char('')
    dp2 = fields.Float('')
    p1 = fields.Float('')
    reactor_temp_high = fields.Char('')
    transducer_failure = fields.Char('')
    set_date_time = fields.Char('')
    btemp = fields.Float('')
    orp = fields.Float('')
    temp_high = fields.Char('')
    lamp_expired = fields.Char('')
    fma = fields.Float('')
    fdr1 = fields.Float('')
    chl = fields.Float('')
    ph = fields.Float('')
    fdr2 = fields.Float('')
    ldr = fields.Float('')
    dp_screen = fields.Float('')
    do = fields.Float('')
    lda = fields.Float('')
    no_dp = fields.Char('')
    utc_date = fields.Date('')
    duty_probe_out = fields.Char('')
    psi = fields.Float('')
    pta = fields.Float('')
    date = fields.Date('')
    high_dp_filter2 = fields.Char('')
    record = fields.Integer('')
    p2 = fields.Float('')
    flow_meter_failure = fields.Char('')
    service_system = fields.Char('')
    filter1_expired = fields.Char('')
    new_text3 = fields.Char('')
    tgu = fields.Float('')
    uv_probe1_failure = fields.Char('')
    filter_data_plc = fields.Many2one('plc.upload','')
    plc_upload_ccp = fields.Many2one('plc.upload','')
    plc_upload_alarm = fields.Many2one('plc.upload','')
    name = fields.Char('')
    uvt = fields.Float('')
